{% set name = "bilby_tgr" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bilby_tgr-{{ version }}.tar.gz
  sha256: a3c1fe9146111ed6d6da1110d332d311d55b2d4cf311aa18849732cb886f0a27
  patches:
    # replace the dependency lalsuite by the actually required subcomponents python-lal
    # and python-lalsimulation, which are not packaged separately on PyPI
    - 0001-minimise-dependencies.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >=3.8
    - bilby
    - python-lal
    - python-lalsimulation >=5.1.0
    - numpy >=1.17

test:
  imports:
    - bilby_tgr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.ligo.org/lscsoft/bilby_tgr
  summary: Testing GR analysis pipelines to use with Bilby
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - adivijaykumar
    - jsteinhoff
    - magathos
